language: php

php:
  - 5.5

services:
  - mysql
  - apache
  - python
  
mysql:
  username: root

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y curl

before_script:
  - ls

script:
  - sleep 5
  - php -l api/v1/index.php
  - php -l setup.php
  - php -l create.php
  - php -l home.php
