language: php

php:
  - '7.0'

services:
  - mysql
  - apache
  - python
  
mysql:
  username: root

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y curl

before_script:
  - ls

script:
  - sleep 5
  - php -l api/index.php
  - php -l setup.php
  - php -l create/index.php
  - php -l client/index.php
