language: php

php:
  - 5.5

services:
  - mysql
  - apache
  
mysql:
  username: root

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y curl

before_script:
  - php -S localhost:8080 &
  - ls

script:
  - sleep 5
  - curl --data "username=root&password=&jitsi=true" http://127.0.0.1:8080/setup.php
